-- =====================================================================
-- Restaurantes Secretos — conteúdo PAGO movido para o servidor.
-- Antes ficava embutido em js/app.js (qualquer um lia no DevTools).
-- Agora vive aqui, protegido por RLS: a anon key NAO le esta tabela.
-- Só o endpoint /api/restaurantes-secretos (que usa a SERVICE KEY e
-- valida a compra) consegue devolver esse conteúdo.
--
-- Como aplicar: Supabase → SQL Editor → cole tudo → Run.
-- =====================================================================

create table if not exists public.restaurantes_secretos (
  id        bigint generated always as identity primary key,
  ordem     int  not null,
  cat       text not null,
  cat_icon  text,
  emoji     text,
  nome      text not null,
  selo      text,
  faixa     text,
  preco     text,
  descricao text,
  publico   text,
  dica      text
);

-- Liga o RLS e NAO cria policy de leitura publica.
-- Resultado: nem a anon key nem usuarios logados leem direto.
-- A service_role (usada no backend) ignora o RLS por padrao.
alter table public.restaurantes_secretos enable row level security;

-- Limpa antes de popular (idempotente — pode rodar de novo sem duplicar).
truncate public.restaurantes_secretos restart identity;

insert into public.restaurantes_secretos
  (ordem, cat, cat_icon, emoji, nome, selo, faixa, preco, descricao, publico, dica)
values
  (1, 'Buffet Livre', '🍽️', '🥩', 'Serra Grill', 'O MELHOR DA CIDADE', 'Médio', 'R$ 75 a R$ 110 por pessoa', 'O topo da categoria em Gramado. Combina a praticidade do buffet com a qualidade de um bom churrasco gaúcho. Buffet vasto, mas o destaque são as carnes grelhadas servidas na mesa.', 'Ambiente amplo, ideal para famílias. Bem localizado, experiência gastronômica excelente para um almoço completo.', 'Chegue um pouco antes das 12h30 na alta temporada para evitar filas.'),
  (2, 'Buffet Livre', '🍽️', '👵', 'Sabor da Nonna', 'MELHOR CUSTO-BENEFÍCIO', 'Econômico', 'R$ 45 a R$ 65 por pessoa', 'Aquela comida caseira com tempero de vó. Preço super justo para os padrões de Gramado, com variedade excelente de pratos quentes, saladas e carnes.', 'Porto seguro do turista que quer comer muito bem, pagar pouco e sentir o sabor da culinária local sem frescuras.', 'Não saia de lá sem provar as sobremesas caseiras incluídas no buffet.'),
  (3, 'Buffet Livre', '🍽️', '♨️', 'Aquecee', NULL, 'Baixo', 'R$ 35 a R$ 60 por pessoa', 'Buffet muito bem servido, focado na culinária do dia a dia com um toque de sofisticação. Comida sempre fresca, quentinha e com ótima reposição.', 'Perfeito para quem está batendo perna pelo centro e quer um almoço rápido, saboroso e com ambiente agradável e climatizado.', NULL),
  (4, 'Buffet Livre', '🍽️', '🇧🇷', 'Ita Brasil', NULL, 'Médio', 'R$ 60 a R$ 80 por pessoa', 'Um dos buffets mais tradicionais da cidade, muito frequentado por moradores locais — sinal de qualidade. Comida simples, honesta, farta e muito saborosa.', 'Se quer economizar de verdade no almoço para investir em um jantar mais caro, o Ita Brasil é a escolha perfeita.', NULL),
  (5, 'Sequência de Fondue', '🫕', '🕯️', 'Belle du Valais', 'O MELHOR DA CIDADE', 'Luxo', 'R$ 350 a R$ 500 por pessoa', 'Um dos melhores restaurantes suíços do Brasil. Ambiente cinematográfico, à luz de velas, com piano ao fundo e atendimento impecável. Ingredientes premium (queijos e chocolates).', 'Não é apenas um jantar, é uma celebração. Perfeito para casais em lua de mel ou comemorações especiais.', 'Exige reserva antecipada. Vá sem pressa para curtir o ritual de cada etapa.'),
  (6, 'Sequência de Fondue', '🫕', '🧀', 'Versoi Fondue', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 110 a R$ 160 por pessoa', 'Entrega a verdadeira experiência do fondue de Gramado (ambiente aconchegante, sequência completa e fartura) por um preço que cabe no bolso. Atendimento ágil.', 'Escolha inteligente pra quem quer viver a noite do fondue tradicional, comer até se fartar, sem estourar o orçamento.', 'Fique atento às opções de reposição: trazem mais queijo, carne e chocolate sempre que pedir.'),
  (7, 'Sequência de Fondue', '🫕', '🏔️', 'D''Montreux', NULL, 'Baixo', 'R$ 60 a R$ 100 por pessoa', 'Ambiente acolhedor e intimista que remete aos chalés alpinos. Sequência de carnes com cortes selecionados e molhos artesanais muito elogiados.', 'Excelente meio-termo: foge do agito das grandes casas de fondue e foca em uma noite agradável e saborosa.', NULL),
  (8, 'Sequência de Fondue', '🫕', '🍫', 'Tomasini', NULL, 'Médio', 'R$ 100 a R$ 150 por pessoa', 'No coração de Gramado, casa super tradicional. Fondue de chocolate é um dos favoritos dos turistas pela qualidade do chocolate artesanal da região.', 'Muito fácil de acessar a pé para quem está hospedado no centro. Excelente estrutura para receber famílias.', NULL),
  (9, 'Italiano / Galeteria', '🍝', '🍷', 'Casa Muttoni', 'O MELHOR DA CIDADE', 'Moderado Alto', 'R$ 200 a R$ 250 por pessoa', 'Imersão na alta gastronomia italiana. Massas de fabricação própria (artesanais e frescas), molhos ricos em sabor e acompanhamentos que elevam o nível.', 'Ambiente lindo e sofisticado. Esqueça a correria de galeteria tradicional; aqui o foco é saborear cada prato com um bom vinho.', 'O galeto ao primo canto deles é incrivelmente crocante por fora e suculento por dentro.'),
  (10, 'Italiano / Galeteria', '🍝', '🍗', 'Galeto Itália', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 90 a R$ 120 por pessoa', 'Clássico rodízio italiano da Serra Gaúcha onde a comida não para de chegar. Sopa de capeletti, galeto, costelinha, vários tipos de massas, polenta e maionese.', 'Vá com muita fome. Lugar perfeito para entender a fama da fartura gastronômica da região sem pagar uma fortuna.', 'A sopa de capeletti que abre os trabalhos é divina, mas guarde espaço para o que vem depois!'),
  (11, 'Italiano / Galeteria', '🍝', '🍾', 'Cantina di Capo', NULL, 'Médio', 'R$ 85 a R$ 130 por pessoa (pratos pra compartilhar)', 'Cantina italiana charmosa, com decoração temática (garrafas de vinho, toalhas xadrez). À la carte, porções muito bem servidas.', 'Excelente para um jantar aconchegante. Lasanha e filé à parmegiana são os grandes destaques.', NULL),
  (12, 'Italiano / Galeteria', '🍝', '👨‍👩‍👧', 'Família Guimarães', NULL, 'Médio', 'R$ 80 a R$ 120 por pessoa', 'Restaurante familiar focado no conforto e sabor tradicional. Pratos clássicos da culinária italiana com ingredientes frescos e muito capricho.', 'Ambiente tranquilo, atendimento acolhedor e pratos que servem muito bem duas ou mais pessoas.', NULL),
  (13, 'Churrascaria / Costela', '🥩', '🔥', 'Chama de Fogo', 'O MELHOR DA CIDADE', 'Luxo', 'R$ 220 a R$ 300 por pessoa', 'Rodízio de carnes nobres de altíssimo padrão (cortes Angus e Hereford, picanha premium, cordeiro, assado de tira). Buffet inclui frutos do mar e queijos finos.', 'A melhor experiência de churrasco da região. Serviço impecável — os garçons são extremamente atentos aos cortes de preferência.', 'Peça o ponto da carne exatamente como gosta; os assadores são mestres nisso.'),
  (14, 'Churrascaria / Costela', '🥩', '🤠', 'Churrascaria Gramadense', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 110 a R$ 150 por pessoa', 'Tradicionalismo e fartura. Espeto corrido completo com os principais cortes gaúchos, mais buffet de saladas honesto, por preço extremamente competitivo.', 'Quer comer o verdadeiro churrasco gaúcho, em ambiente familiar, sem frescura e com preço justo? Escolha certa.', NULL),
  (15, 'Churrascaria / Costela', '🥩', '✨', 'Gramado & Brasa', NULL, 'Moderado Alto', 'R$ 140 a R$ 190 por pessoa', 'Churrascaria moderna que une o clássico espeto corrido com cortes contemporâneos. Ambiente bonito, bem iluminado e confortável.', 'Ótima localização e excelente buffet de saladas. Agrada quem foca nas carnes e quem gosta de bons acompanhamentos.', NULL),
  (16, 'Churrascaria / Costela', '🥩', '🛞', 'Churrascaria Roda de Carroça', NULL, 'Médio', 'R$ 120 a R$ 160 por pessoa', 'Imersão na cultura gaúcha. Ambiente rústico remete às tradições do campo, e o forte aqui é o costelão 12 horas e os cortes tradicionais assados na brasa.', 'Perfeito para quem busca atmosfera mais rústica e cultural durante a refeição.', NULL),
  (17, 'Pizzaria', '🍕', '🪵', 'Forneria 847', 'O MELHOR DA CIDADE', 'Médio', 'R$ 100 a R$ 130 por pessoa', 'Pizzas artesanais de massa leve (longa fermentação) e ingredientes selecionados de alta qualidade. Estilo napolitano, assada em forno de alta temperatura.', 'Se prefere qualidade à quantidade e quer fugir da agitação dos rodízios, a Forneria oferece ambiente descolado e pizzas sofisticadas.', 'Harmonize a pizza com os coquetéis da casa ou uma cerveja artesanal local.'),
  (18, 'Pizzaria', '🍕', '🔁', 'Scur Pizzaria', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 90 a R$ 130 por pessoa', 'Rodízio de pizza mais famoso e tradicional de Gramado. Dezenas de sabores passando sem parar (salgadas e doces), massa fina, muito recheio + buffet de massas e petiscos.', 'Diversão e fartura garantidas para toda a família. Serviço rápido e custo-benefício imbatível na categoria de rodízio.', NULL),
  (19, 'Pizzaria', '🍕', '🦒', 'Kongo Pizzaria', 'MELHOR EXPERIÊNCIA TEMÁTICA', 'Moderado Alto', 'R$ 160 a R$ 190 por pessoa', 'Imersão na selva do Congo. Decorada como floresta tropical, com animais animatrônicos, sons da natureza e pocket shows teatrais a cada hora.', 'Obrigatório se está viajando com crianças. Experiência visual e entretenimento compensam cada centavo.', 'Chegue cedo ou faça reserva antecipada no site para evitar as gigantescas filas na porta.'),
  (20, 'Pizzaria', '🍕', '🌲', 'The Petit (Canela)', NULL, 'Médio', 'R$ 70 a R$ 100 por pessoa', 'Na cidade vizinha Canela. Pizzaria super charmosa e aconchegante. Ambiente intimista e pizzas com combinações criativas.', 'Excelente desculpa para esticar o passeio até Canela no fim do dia e jantar em um lugar acolhedor.', NULL),
  (21, 'Lanches Rápidos / Burgers', '🍔', '🐶', 'Cusco Burger', 'MELHOR CUSTO-BENEFÍCIO', 'Econômico', 'R$ 45 a R$ 65 por pessoa', 'Hamburgueres artesanais premium com identidade gaúcha ("Cusco" é gíria local para cachorro). Carnes altas, suculentas, grelhadas no fogo, excelentes combinações de queijos.', 'Burgers com qualidade de metrópole, mas com alma da Serra Gaúcha. Preço excelente pela qualidade gourmet.', 'Peça a batata rústica com tempero da casa para acompanhar.'),
  (22, 'Lanches Rápidos / Burgers', '🍔', '🥙', 'Gnomo Lanches', NULL, 'Econômico', 'R$ 40 a R$ 60 por pessoa', 'Lanchonete mais tradicional do centro de Gramado. Grande destaque é o autêntico Xis Gaúcho — sanduíche gigante prensado que vale por uma refeição completa.', 'Se não é do RS, precisa provar o "Xis". Fica bem na avenida principal, perfeito para observar o movimento da cidade.', NULL),
  (23, 'Lanches Rápidos / Burgers', '🍔', '🦅', 'Águia Lanches', NULL, 'Econômico', 'R$ 35 a R$ 55 por pessoa', 'Outro gigante dos lanches tradicionais e do Xis. Perfeito para um lanche rápido na madrugada ou fim de noite. Porções generosas, maionese caseira artesanal deliciosa.', 'Ambiente simples, focado em sabor, rapidez e fartura. Muito procurado por quem quer fugir dos preços turísticos do centro.', NULL),
  (24, 'Lanches Rápidos / Burgers', '🍔', '🍟', 'McDonald''s de Gramado', NULL, 'Econômico', 'R$ 35 a R$ 55 por pessoa', 'Cardápio padrão mundial, mas com um diferencial único: a arquitetura. A unidade de Gramado parece um chalé europeu alpino de madeira, super fotogênico.', 'Ideal pra quem viaja com crianças que não abrem mão do McLanche Feliz, ou pra aquele lanche rápido. Vale a visita só pela fachada!', NULL),
  (25, 'Cafeterias', '☕', '☕', 'Quiero Café', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 35 a R$ 60 por pessoa', 'Cardápio gigantesco que atende desde o café da manhã até o jantar. Ótimos combos de café, lanches, waffles, doces e pratos expressos com preço muito competitivo para a região.', 'Ambiente moderno, atendimento rápido e ótimo para quem quer comer bem sem gastar muito. Abre cedo e fecha tarde — um verdadeiro coringa na viagem.', NULL),
  (26, 'Cafeterias', '☕', '🧙‍♀️', 'Casa da Velha Bruxa', NULL, 'Moderado Alto', 'R$ 55 a R$ 90 por pessoa', 'Uma das docerias mais tradicionais e nostálgicas de Gramado, bem ao lado da Rua Torta. Famosa pelas sobremesas históricas feitas com chocolate artesanal Prawer, como o ícone "Sorvete ao Forno" e os waffles com calda quente.', 'Clássico da cidade, mas o preço acompanha a fama e a localização. Vale mais pela experiência histórica e pelo ponto turístico do que pelo custo-benefício puro.', 'As sobremesas e cafés aqui têm valor de grife — vá ciente disso. Foque no famoso "Sorvete ao Forno" para uma única indulgência inesquecível.'),
  (27, 'Cafeterias', '☕', '⛪', 'Padaria São Pedro', NULL, 'Moderado Alto', 'R$ 40 a R$ 70 por pessoa', 'Localizada estrategicamente bem atrás da Igreja Matriz São Pedro. Oferece enorme variedade de salgados, folhados, tortas e as famosas cucas gaúchas frescas.', 'Por estar no ponto mais central e movimentado de Gramado, os preços são inflacionados. Vale pela conveniência de um lanche rápido entre um ponto turístico e outro — não espere preço de "padaria de bairro".', NULL),
  (28, 'Recreação / Espaço Kids', '🧸', '🏰', 'Restaurante Höppner', 'O MELHOR DA CIDADE', 'Luxo', 'R$ 150 a R$ 250 por pessoa', 'Junto ao tradicional Hotel Ritta Höppner, é sinônimo de elegância. Serve o clássico café da tarde inglês e pratos alemães impecáveis. O espaço kids é de altíssimo padrão, com monitoria e brinquedos lúdicos.', 'Uma das experiências mais acolhedoras da cidade para quem viaja com crianças pequenas, unindo alta gastronomia com sossego para os pais.', NULL),
  (29, 'Recreação / Espaço Kids', '🧸', '🍝', 'Mamma Mia', 'MELHOR CUSTO-BENEFÍCIO', 'Médio', 'R$ 95 a R$ 130 por pessoa', 'Uma das galeterias mais famosas da região. A fartura de massas, galetos e polentinhas agrada muito o paladar infantil. A unidade de Gramado tem um excelente espaço kids estruturado para os pequenos gastarem energia.', 'Perfeito para o clássico e farto almoço de domingo em família.', NULL),
  (30, 'Recreação / Espaço Kids', '🧸', '🍇', 'Campo & Vinho', NULL, 'Econômico', 'R$ 60 a R$ 110 por pessoa', 'Super versátil. Durante o dia entrega um buffet livre completo com ótimo preço; à noite o foco vira as pizzas. Conta com uma área kids muito bem montada para entreter as crianças durante a refeição.', 'Opção prática, sem frescuras e muito cômoda para qualquer hora do dia.', 'Aproveite o melhor dos dois mundos: vá pra um almoço de buffet em família e volte outro dia pra noite de pizza.'),
  (31, 'Recreação / Espaço Kids', '🧸', '🥩', 'Steak House — Carne & Osso', NULL, 'Moderado Alto', 'R$ 120 a R$ 180 por pessoa', 'Especializada em cortes de carnes premium, assados na brasa com muita precisão. Ambiente moderno e espaço kids seguro e estruturado para receber as famílias.', 'Ótima pedida para quem quer saborear uma carne de primeira linha enquanto os filhos brincam no espaço recreativo.', NULL),
  (32, 'Recreação / Espaço Kids', '🧸', '🔥', 'El Fuego', NULL, 'Moderado Alto', 'R$ 130 a R$ 220 por pessoa', 'Restaurante tradicional bem no centro de Gramado, famoso por carnes e pela sequência de fondue. Possui área infantil planejada para que os pais consigam curtir o jantar (especialmente o ritual do fondue) com calma.', 'Localização imbatível no centro e excelente estrutura familiar.', NULL),
  (33, 'Recreação / Espaço Kids', '🧸', '🌲', 'The Petit', NULL, 'Médio', 'R$ 70 a R$ 100 por pessoa', 'O ambiente acolhedor e intimista da Petit reserva um cantinho especial para os pequenos. Enquanto as pizzas de massa leve são servidas, as crianças têm espaço dedicado para se distrair.', 'Ótima opção para quem busca ambiente confortável com espaço kids, sem a aglomeração dos grandes rodízios.', NULL),
  (34, 'Recreação / Espaço Kids', '🧸', '🍽️', 'Dos Cocina', NULL, 'Moderado Alto', 'R$ 120 a R$ 190 por pessoa', 'Pratos sofisticados, apresentações lindas e cardápio muito bem executado. O grande diferencial é conseguir aliar essa proposta gastronômica mais moderna com ótimo atendimento e espaço para crianças.', 'Ideal para os pais que não querem abrir mão de um jantar gastronômico sofisticado, mas precisam da comodidade de uma área infantil.', NULL);
